#ifndef DCMTKLIB
#define DCMTKLIB
#include <algorithm>
#include <QProcess>
#include <QMessageBox>
#include <QStringList>
#include <QStringListIterator>
#include <string.h>
#include <QFileDialog>
#include <QMessageBox>
#include <string.h>
#include <QFileDialog>
#include <QMainWindow>
#include <iostream>
#include <cstdlib>
#include <string>
#include <stdio.h>
#include <QPixmap>
#include <QMainWindow>
#include <iostream>
#include <cstdlib>
#include <string>
#include <stdio.h>
#include <QPixmap>
#include <QXmlStreamReader>
#include <QXmlStreamWriter>
#include <iostream>
#include <QXmlReader>
#include <QDialog>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QGraphicsItem>
#include <limits.h>
#include <string.h>
#include <QtXml>
#include <stdint.h>
#include <limits>
#include <cstddef>
#include <QXmlSimpleReader>
#include <iostream>
#include <QMessageBox>
#include <QFileDialog>
#include <QPointer>
#include "dcmtk/config/osconfig.h"
#include "dcmtk/dcmdata/dcdatset.h"
#include "dcmtk/dcmdata/dccodec.h"
#include "dcmtk/dcmdata/dcdict.h"
#include "dcmtk/dcmdata/dctk.h"
#include "dcmtk/dcmimgle/dcmimage.h"
#include "dcmtk/dcmimage/diregist.h"
#include "dcmtk/dcmimgle/dcmimage.h"
#include "dcmtk/dcmimgle/dipixel.h"
#include "dcmtk/dcmimgle/diimage.h"
#include "dcmtk/dcmimgle/dimo1img.h"
#include "dcmtk/dcmimgle/dimo2img.h"
#include "dcmtk/config/osconfig.h"
#include "dcmtk/dcmdata/dctk.h"
#include "dcmtk/dcmimgle/dcmimage.h"
#include "dcmtk/dcmimage/diregist.h"
#include "dcmtk/dcmjpeg/djencode.h"
#include "dcmtk/dcmjpeg/djdecode.h"
#include "dcmtk/dcmdata/libi2d/i2dbmps.h"
#include <dcmtk/dcmimgle/dcmimage.h>
#include <dcmtk/dcmdata/dcrledrg.h> /* for DcmRLEDecoderRegistration */
#include <dcmtk/dcmjpeg/djdecode.h> /* for dcmjpeg decoders */
#include <dcmtk/dcmjpeg/dipijpeg.h> /* for dcmimage JPEG plugin */
#include <dcmtk/dcmimage/diregist.h>
#include "dcmtk/dcmdata/dcfilefo.h"
#include "dcmtk/dcmimgle/dcmimage.h"
#include <QFileDialog>
#include <QMainWindow>
#include <iostream>
#include <cstdlib>
#include <string>
#include <QPixmap>
//#include <mdfdsman.h>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <QBitmap>
#include <QBuffer>
#include <iostream>
#include <vector>
#include <string>
//#include <msclr\marshal_cppstd.h>
#include <cmath>
#include "dcmtk/dcmdata/dcfilefo.h"
#include "dcmtk/dcmimgle/dcmimage.h"
#include <stdio.h>
#include <stdlib.h>
#include <QFile>
#include <QTextStream>
#include <math.h>
#include <QImage>
#include <QRgb>
#include <QDebug>
#include <QPoint>
#include <iostream>
#include <fstream>

#include <QString>
#include <QStringList>
#endif // DCMTKLIB

